5th_Contact_Session_Assignment/Lotify_Music_player/Lotify_Music_player/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('Music_player.urls')),
]

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/urls.py
from django.urls import path


from . import views
app_name = 'Music_player'

urlpatterns = [

    path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),

    path('dashboard/<slug:slug>/', views.play_music, name='play_music'),

]

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/models.py
from django.db import models
from django.forms import ValidationError
import magic
import uuid


# validate the incoming audio file
def validate_audio_file(file):
    mime = magic.Magic(mime=True)
    file_mime_type = mime.from_buffer(file.read())
    if not file_mime_type.startswith('audio/'):
        raise ValidationError(
            'Invalid file type. Only audio files are allowed.')


uid = uuid.uuid4()
class Music(models.Model):
    slug = models.SlugField(default=uid, editable=False)
    music_icons = models.ImageField(blank=False)
    music_title = models.CharField(max_length=100, null=False)
    audio_file = models.FileField(null=False, validators=[validate_audio_file])
    artist_name = models.CharField(max_length=100, null=False)
    albumName_or_playlistName = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class PlayList_or_Album(models.Model):
    slug = models.SlugField(default=uid, editable=False)
    PlayList_or_AlbumName = models.CharField(max_length=100, null=False)
    play_list_cover_image = models.ImageField(blank=False)
    songs = models.ManyToManyField(
        Music, related_name='playlists_or_albums')
    artist_name = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        matching_songs = Music.objects.filter(
            albumName_or_playlistName=self.PlayList_or_AlbumName)
        self.songs.set(matching_songs)

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/views.py
from django.shortcuts import render
from . import models
# Create your views here.


def index(request):
    return render(request, 'Music_player/landingpage.html')

def dashboard(request):
    query = request.GET.get('q')
    results = None
    if query:
        results = models.PlayList_or_Album.objects.filter(
            PlayList_or_AlbumName__icontains=query)
    if results:
        print(results.all(),"results")
    playlists = models.PlayList_or_Album.objects.all()
    print(playlists,"playlists")
    return render(request, 'Music_player/dashboard.html',{'playlists':playlists,'results':results})


def play_music(request, slug):
    playlist = models.PlayList_or_Album.objects.filter(slug=slug).first()
    if not playlist:
        return render(request, 'Music_player/404.html')
    return render(request, 'Music_player/dashboard_playmusic.html', {'playlist': playlist})

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/templates/Music_player/dashboard.html
{% extends 'Music_player/layout_dash.html' %}
{% load static %}




{% block title %}
    Lotify | Dashboard
{% endblock title %}



{% block content %}
    <div class="container">
                <div class="preview_playlist">
                    <div class="title">
                        <h2>Focus Calm Songs</h2>
                        <button>See More</button>
                    </div>
                    <div class="preview_playlist_card_cont" id="">
                        
                        {% for playlist in playlists %}
                        <div class="card" id='card' onClick="LocChange('{{playlist.slug}}')">
                            <div class="imageholder">
                                <img
                                 src="{{playlist.play_list_cover_image.url}}"
                                  alt="Playlist{{playlist.PlayList_or_AlbumName}}"
                                  >
                            </div>
                            <div class="card_info">
                                <h3>{{playlist.PlayList_or_AlbumName}}</h3>
                                <p class="clamp">{{playlist.artist_name}}</p>
                            </div>
                        </div>
                            
                        {% endfor %}
                            
                    </div>

                </div>
                <div class="preview_playlist">
                    <div class="title">
                        <h2>Oracle Playlist</h2>
                        <button>See More</button>
                    </div>
                    <div class="preview_playlist_card_cont" id="preview_playlist_card_cont2v">
                         <div class="card">
                                            <div class="imageholder"><img src="{% static 'images/playlist1.png'%}" alt="Playlist"></div>
                                            <div class="card_info">
                                                <h3>Focus</h3>
                                                <p class="clamp">By Oracle</p>
                                            </div>
                                        </div> 
                    </div>

                </div>
            </div>
{% endblock content %}
    


{% block search_result %}
  
  {% for result in results.all %}
            
 
    
    <div class="result_card" onClick="LocChange('{{result.slug}}')">
              <div class="imageholder_infoHolder">
                <img src="{{result.play_list_cover_image.url}}" alt="music" />
                <div class="card_info">
                  <h3 title="Focus on your self you brat">{{result.PlayList_or_AlbumName}}</h3>
                  <p class="clamp">By:{{result.artist_name}}</p>
                </div>
              </div>
              <div>
                <i class="bi bi-three-dots-vertical"></i>
              </div>
            </div>
  {% endfor %}
    
            
           
{% endblock search_result %}
    

{% block js_script %}
    <script src="{% static 'js/dashboard.js' %}"></script>
{% endblock js_script %}
    

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/templates/Music_player/dashboard_playmusic.html
{% extends 'Music_player/layout_dash.html' %}
{% load static %}




{% block title %}
    Lotify | Dashboard | PlayMusic
{% endblock title %}



{% block content %}
<div class="pl_container_detail">
                <div class="header">
                    <img src="{{playlist.play_list_cover_image.url}}" alt="">
                    <div>
                        <p>playlist</p>
                        <h1>{{playlist.PlayList_or_AlbumName}}</h1>
                        <p class="description">Keep calm and focus with ambient and post-rock music.</p>
                        <p>
                            <span>Lotify</span>
                            <span>3,940,865 likes</span>
                            <span>252 songs,</span>
                            <span>about 10 hr</span>
                        </p>
                    </div>
                </div>
                <div class="controllers">
                    <img src="{% static 'images/playicon.png'%}" alt="playicon">
                    <span><i class="bi bi-heart"></i></span>
                    <span><i class="bi bi-three-dots"></i></span>
                </div>
                <div class="playlist_table_cont">
                    <table>
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Artist</th>
                                <th>Album</th>
                                <th>Time</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for song in playlist.songs.all %}
                                <tr onClick="MusicListClick('/media/{{song.audio_file}}','/media/{{song.music_icons}}','{{song.music_title}}')">
                                <td>{{ forloop.counter }}</td>
                                <td title="{{ song.music_title }}">{{ song.music_title }}</td>
                                <td>{{ song.artist_name }}</td>
                                <td>{{ song.albumName_or_playlistName }}</td>
                                <td>5:00</td>
                            </tr>
                            {% endfor %}
                                
                            
                            {% comment %} <tr>
                                <td>2</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>8</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:08</td>
                            </tr>
                            <tr>
                                <td>9</td>
                                <td>Intro</td>
                                <td>The xx</td>
                                <td>xx</td>
                                <td>2:09</td>
                            </tr> {% endcomment %}
                    </table>
                </div>
                <div class="music_player">
                    <audio
                        src="{% static 'images/lost-in-dreams-abstract-chill-downtempo-cinematic-future-beats-270241.mp3'%}" id="audio_player"></audio>
                    <div class="controller_for_music_player_cont">
                        <div class="music_details">
                            <img src="{% static 'images/playlisttwox.png'%}" id="music_icon" alt="">
                            <p class="clamp_one_line" id="music_title">Deep Focus</p>
                        </div>
                        <div class="music_controller">
                            <div class="time_loader">
                                <span id="time_played_display">0:00</span>
                                <div class="time_loader_cont">
                                    <div class="time_loader_bar" id="time_loader_bar"></div>
                                </div>
                                <span id="music_duration_display">3:45</span>
                            </div>
                            <div class="music_controller_left">
                                <button><i class="bi bi-shuffle"></i></button>
                                <button><i class="bi bi-skip-start-fill"></i></button>
                                <button class="play" id="play_btn"><i class="bi bi-play-fill"></i></button>
                                <button><i class="bi bi-skip-end-fill"></i></button>
                                <button><i class="bi bi-repeat"></i></button>
                            </div>
                        </div>
                        <div class="volume_mute">
                            <button id="volume_mute"><i class="bi bi-volume-up-fill"></i></button>

                        </div>
                    </div>
                </div>
                </div>

{% endblock content %}
    

{% block js_script %}
       <script src="{% static 'js/dasboardtwo.js'%}"></script>
{% endblock js_script %}
    

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/templates/Music_player/landingpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/landingpage.css' %}" />
    <title>Lotify</title>
</head>

<body>
    <main>
        <section class="hero_section">
            <div class="hero_side_one">
                <img src="{% static 'images/hero_background_one.png' %}" class="hero_sideone_backgroud_image" alt="" srcset="">
                <div class="SD_one_container">
                    <nav>
                        <a href="#">
                            <img src="{% static 'images/spotify.png' %}" alt="" srcset="" class="logo_hr">
                            <h2>Lotify</h2>
                        </a>
                    </nav>
                    <div class="title">
                        <h1>Discover a world of music with Lotify</h1>
                    </div>
                    <div class="description">
                        <p>Welcome to Spotify, where music comes alive. Experience a universe of endless tunes,
                            handpicked playlists, and
                            personalized recommendations just for you.</p>
                    </div>
                    <div class="btn_herox">
                        <a href="#" class="download_hr_btn">
                            <span>Download the app</span>
                            <img src="{% static 'images/download_icons.png' %}" alt="" srcset="">
                        </a>
                        <a href="{%url 'Music_player:dashboard'%}" class="download_hr_btn center_it_hb">
                            <span>Play on web</span>
                            <img src="{% static 'images/www.png' %}" alt="" srcset="">
                        </a>
                    </div>
                    <div class="users_hr_dis">
                        <img src="{% static 'images/hero_users_dis.png'%}" alt="">
                        <span>517.69 million+ <br>
                            Spotify users worldwide</span>
                    </div>
                </div>
            </div>
            <div class="hero_sidetwo">
                <img src="{% static 'images/backgroundherotwoimage.png' %}" class="hero_sidetwo_backgroud_image" alt="" srcset="">
                <div class="hero_sidetwo_cont">
                    <nav>
                        <ul>
                            <li><a href="#">Premium</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Download</a></li>
                            <li><a href="#">More...</a></li>
                        </ul>
                    </nav>
                    <div class="image_dis_cont">
                        <img src="{% static 'images/sportiylogoone.png' %}" class="spoti_back_image" alt="">
                        <img src="{% static 'images/phone_hand.png' %}" class="phone_hand_image" alt="">
                        <img src="{% static 'images/playershowone.png' %}" class="player_show_image_one" alt="">
                        <img src="{% static 'images/playershowtwo.png' %}" class="player_show_image_two" alt="">
                    </div>
                </div>
            </div>
        </section>
        <section class="download_app_section">
            <h2>Scan To Download Spotify App</h2>
            <div class="download_app_img_cont">
                <img src="{% static 'images/down_code_.png' %}" alt="">
            </div>
        </section>
        <section class="music_jorney_section">
            <div class="title_mjs">
                <h2>Enhance Your Music Journey with Premium</h2>
                <p>Upgrade to Spotify Premium and take your music journey to the next level. Enjoy uninterrupted music
                    playback, even in
                    offline mode. Say goodbye to those pesky ads, and indulge in high-quality audio for a truly
                    immersive experience.
                </p>
            </div>
            <div class="features">
                <div class="card">
                    <img src="{% static 'images/freemxcxe.png'%}" alt="">
                    <p class="title">Ad-free music listening</p>
                    <p class="description">Enjoy uninterrupted music</p>
                </div>
                <div class="card">
                    <img src="{% static 'images/offlinexksos.png'%}" alt="">
                    <p class="title">Offline playback</p>
                    <p class="description">Save your data by listening offline</p>
                </div>
                <div class="card">
                    <img src="{% static 'images/musicxhsgdhsue.png'%}" alt="">
                    <p class="title">Play everywhere</p>
                    <p class="description">Listen on your speakers,<br> TV and other favorite devices</p>
                </div>
                <div class="card">
                    <img src="{% static 'images/payshdhues.png'%}" alt="">
                    <p class="title">Pay your way</p>
                    <p class="description">Prepay with Patm, UPI, and more.</p>
                </div>
            </div>
        </section>
        <section class="prices_section">
            <div class="title">
                <h2>Pick Your Premium</h2>
                <p>Upgrade to Spotify Premium and take your music journey to the next level. Enjoy uninterrupted music
                    playback, even in offline mode</p>
                <img src="{% static 'images/payment_company.png'%}" alt="image">
            </div>
            <div class="prices_card_cont">
                <div class="card">
                    <div class="avb_box">
                        <p>One-time plan available</p>
                    </div>
                    <div class="description">
                        <h2>Mini</h2>
                        <p>From $7/day</p>
                        <p>one account on mobile only</p>
                    </div>
                    <div class="div_line"></div>
                    <div class="features">
                        <ul>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Ad free music</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Download more than 30 songs on one mobile device</p></li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Group session</p>
                            </li>
                        </ul>
                    </div>
                    <button>View Plans</button>
                </div>
                <div class="card">
                    <div class="avb_box">
                        <p>One-time plan available</p>
                    </div>
                    <div class="description">
                        <h2>Individual</h2>
                        <p>From $117/day</p>
                        <p>One account </p>
                    </div>
                    <div class="div_line"></div>
                    <div class="features">
                        <ul>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Ad free music</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Download more than 10k songs on one mobile device</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Group session</p>
                            </li>
                        </ul>
                    </div>
                    <button>View Plans</button>
                </div>
                <div class="card duo_g_border">
                    <div class="avb_box">
                        <p>One-time plan available</p>
                    </div>
                    <div class="description">
                        <h2>Duo</h2>
                        <p>From $309/day</p>
                        <p>Two account</p>
                    </div>
                    <div class="div_line"></div>
                    <div class="features">
                        <ul>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>For couples </p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Ad free music</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Download more than 30 songs on one mobile device</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Group session</p>
                            </li>
                        </ul>
                    </div>
                    <button>View Plans</button>
                </div>
                <div class="card">
                    <div class="avb_box">
                        <p>One-time plan available</p>
                    </div>
                    <div class="description">
                        <h2>Family</h2>
                        <p>From $500/day</p>
                        <p>Up to 6 accounts</p>
                    </div>
                    <div class="div_line"></div>
                    <div class="features">
                        <ul>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>For family who live together</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Block explicit content</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Ad free music</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Download more than 30 songs on one mobile device</p>
                            </li>
                            <li>
                                <img src="{% static 'images/checkmark.png'%}" alt="">
                                <p>Group session</p>
                            </li>
                        </ul>
                    </div>
                    <button>View Plans</button>
                </div>
            </div>
        </section>
        <section class="student_discount">
            <div>
                <h2>Enjoy Premium Features with Our Student Discount!</h2>
                <p>Spotify loves students, and we've got a special treat for you! Elevate your music experience without breaking the bank.
                Unlock all the premium features you love at an exclusive student discount.</p>
                <button>Learn more</button>
            </div>
        </section>
        <footer>
            <div class="logo">
                <img src="{% static 'images/spotify.png'%}" alt="" srcset="">
                <h2>Lotify</h2>
            </div>
            <div class="links_one">
                <ul>
                    <li>company</li>
                    <li>about</li>
                    <li>jobs</li>
                    <li>for the record</li>
                </ul>
            </div>
            <div class="links_one">
                <ul>
                    <li>company</li>
                    <li>artist</li>
                    <li>investors</li>
                    <li>vendors</li>
                    <li>advertisers</li>
                    <li>developers</li>
                </ul>
            </div>
            <div class="links_one">
                <ul>
                    <li>useful links</li>
                    <li>support</li>
                    <li>web player</li>
                    <li>free mobile app</li>
                </ul>
            </div>
            <div class="socails">
                <img src="{% static 'images/facebook.png'%}" alt="" srcset="">
            <img src="{% static 'images/twitter.png'%}" alt="" srcset="">
                <img src="{% static 'images/instagram.png'%}" alt="" srcset="">
            </div>
        </footer>
    </main>
</body>

</html>

5th_Contact_Session_Assignment/Lotify_Music_player/Music_player/templates/Music_player/layout_dash.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/dasboard.css'%}" />
    <title>{% block title %} Lotify {% endblock title %}</title>
  </head>

  <body>
    <main>
      <aside class="dash_aside">
        <a href="/" class="logo_link">
          <div class="logo">
            <img src="{% static 'images/spotify.png'%}" alt="Lotify" />
            <h1>Lotify</h1>
          </div>
        </a>
        <div class="menu_one">
          <ul>
            <li>
              <a href="/dashboard/"
                ><i class="bi bi-house-door-fill"></i><span>Home</span></a
              >
            </li>
            <li>
              <a href=""><i class="bi bi-search"></i><span>Search</span></a>
            </li>
            <li>
              <a href=""
                ><i class="bi bi-collection"></i><span>Library</span></a
              >
            </li>
          </ul>
        </div>
        <div class="menu_two">
          <ul>
            <li>
              <a href=""
                ><i class="bi bi-plus-square-fill"></i
                ><span>Create Playlist</span></a
              >
            </li>
            <li>
              <a href=""
                ><i class="bi bi-heart-fill"></i><span>Liked Songs</span></a
              >
            </li>
          </ul>
        </div>
        <div class="footer">
          <ul>
            <li>Legal</li>
            <li>Privacy Center</li>
            <li>Policy Center</li>
            <li>Cookies</li>
            <li>Ads</li>
            <li>About</li>
          </ul>
        </div>
        <div class="currentLang">
          <i class="bi bi-globe-europe-africa"></i><span>English</span>
        </div>
      </aside>
      <section class="dash_section">
        <div class="topbar">
          <div class="search">
            <div class="hm_xs">
              <i class="bi bi-house-door-fill"></i>
            </div>
            <div class="searchbar">
              <input type="search" placeholder="Search" id="search_input" />
              <div class="line_div_se"></div>
              <button id="search_input_button">
                <i class="bi bi-search"></i>
              </button>
            </div>
          </div>
        </div>
        <div class="search_result_modal" id="search_result_modal">
          <div class="title">
            <h2>Result:200</h2>
            <button id="search_result_modal_close_btn">
              <span>close</span> <i class="bi bi-x-circle"></i>
            </button>
          </div>
          <div class="result_cont" id="result_cont">
           
           {% block search_result %}
            
           {% endblock search_result %}
            
          </div>
        </div>
        {% block content %} {% endblock content %}
      </section>
    </main>

    {% block js_script %} 

    {% endblock js_script %}
    <script src="{% static 'js/layout_dash.js' %}"></script>
  </body>
</html>

 {% comment %} <div class="result_card">
              <div class="imageholder_infoHolder">
                <img src="assets/playlisttwox.png" alt="music" />
                <div class="card_info">
                  <h3 title="Focus on your self you brat">Focus Cu*</h3>
                  <p class="clamp">By: Spotify</p>
                </div>
              </div>
              <div>
                <i class="bi bi-three-dots-vertical"></i>
              </div>
            </div>
            <div class="result_card">
              <div class="imageholder_infoHolder">
                <img src="assets/playlisttwox.png" alt="music" />
                <div class="card_info">
                  <h3 title="Focus on your self you brat">Focus Cu*</h3>
                  <p class="clamp">By: Spotify</p>
                </div>
              </div>
              <div>
                <i class="bi bi-three-dots-vertical"></i>
              </div>
            </div>
            <div class="result_card">
              <div class="imageholder_infoHolder">
                <img src="assets/playlisttwox.png" alt="music" />
                <div class="card_info">
                  <h3 title="Focus on your self you brat">Focus Cu*</h3>
                  <p class="clamp">By: Spotify</p>
                </div>
              </div>
              <div>
                <i class="bi bi-three-dots-vertical"></i>
              </div>
            </div> {% endcomment %}